# Generated by Django 2.2.1 on 2019-06-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='favicon',
            field=models.ImageField(default='null.png', upload_to='favicons'),
        ),
    ]
